exports.handler = async function (event, context) {
    const mensagens = [
"GAME THEROY: Gardevoir is Parda??? • pepfefeusson • 11/23/2023",
"btw, é incrivel o quão real é a teoria de 'quanto mais ao norte o gaúcho viaja, mais ele encontra argentino no caminho' • pepfefeusson •  • 2/15/2025 • ",
"*tecnica da toranja* • pepfefeusson • 1/31/2025",
"psicologia por osmose • ciroel • 1/31/2025",
"eu acho que tu NAO quer falar desse assunto • ciroel • 1/31/2025 • ",
"Atenas antiga assim: • ciroel • 1/31/2025 • ",
"segredos de mulher • ciroel • 1/31/2025 • ",
"consigo vencer pokemon emerald apenas com meu afilhado de 2 anos?? • pepfefeusson • 1/27/2025 • ",
" Lairon José • ciroel • 1/27/2025 • ",
"MANDOU UM QUÉCIO • pepfefeusson • 1/24/2025 • ",
"e digamos que tu ganhe um magikarp no jogo do bicho • pepfefeusson • 1/24/2025 • ",
"OW, santos dummont mecha com a 14 bis • pepfefeusson • 1/17/2025 • ",
"mastigarei teus fones de ouvido • pepfefeusson • 1/17/2025 • ",
"o fandon do grind está morrendo, retweete se você é um Grinder também • vickthehuman • 1/14/2025 • ",
"manda audio peidando • pepfefeusson • 1/9/2025 • ",
"anota apenas este • pepfefeusson • 1/2/2025 • ",
"se for praia do arrombado de novo • pepfefeusson • 1/2/2025 • ",
"controle de n64 hetero cis • pepfefeusson • 1/2/2025 • ",
"Eu nao acredito que o teu poder de voto é o mesmo que o meu • ciroel • 12/25/2024 • ",
"ciroel <3 LULA 13 • ciroel • 12/25/2024 • ",
"yooka laylee tem uma personagem mulher geladeira que eu chamo de 'Sheiladeira' e eu me cago rindo me achando o apogeu do humor • pepfefeusson • 12/23/2024 • ",
"A terra é esfera • pepfefeusson • 12/20/2024 • ",
"ta viado, vai, mata o aliza e a teta com um wurmple ent desgraça • pepfefeusson • 12/19/2024 • ",
"'como abbortar com 27 anos' • pepfefeusson • 12/19/2024 • ",
"posso ir ao banheiro [plateia desenvolve um buraco negro de tanto rir] • ciroel • 12/5/2024 • ",
" português fumante: vou fmar um sgarro • pepfefeusson • 12/2/2024 • ",
"chupa minha cuce <3 inha aqui ó • vickthehuman • 11/29/2024 • ",
 "xoxo <3 a • vickthehuman • 11/29/2024 • ",
 "brasileiras batem tchecas na final do volei de praia • pepfefeusson • 11/29/2024 • ",
 "Tags: et bilu, sexo, fisting • pepfefeusson • 11/29/2024 • ",
 "eu sorreio das minhas proprias piadas se nao ngm vai • pepfefeusson • 11/29/2024 • ",
 "Carapicuíba - SP • pepfefeusson • 11/28/2024 • ",
 "manda o ''tudo que vai volta, taca a buceta que eu taco a piroca'' • pepfefeusson • 11/26/2024 • ",
"cadê a mona?? cade elah???? • ciroel • 11/22/2024 • ",
"-morador de Pelotad • ciroel • 11/22/2024 • ",
"@mods banam 'Rafael' • pepfefeusson • 11/8/2024 • ",
"eu joguei guacamelee em espanhol e o super soco do jogo se chamava Puñetazo • pepfefeusson • 11/8/2024 • ",
"when you are comendo a pastel and there's um ovo cortado na metade no meio • pepfefeusson • 11/5/2024 • ",
"minha nossa cenoura • pepfefeusson • 10/28/2024 • ",
"amo sorvete napolitano, o creme com gosto de fronha, o morango com gosto de axila, o chocolate com gosto de sebo • pepfefeusson • 10/22/2024 • ",
"joguei um ímã no meu café sem querer • pepfefeusson • 10/21/2024 • ",
"meu nome é cuceTinha e eu Tenho uma cuceTa • pepfefeusson • 10/15/2024 • ",
"CUCETORONTE • pepfefeusson • 10/15/2024 • ",
"eu assinei amazon prime sem querer • pepfefeusson • 10/15/2024 • ",
"deu bocejinho, Tem que dar o cuzinho • pepfefeusson • 10/6/2024 • ",
"meu cerebro Ta fazendo o cu piscando • pepfefeusson • 10/6/2024 • ",
"pepfefeusson: 'o assopra cu' sRaffaello: 'ja..... me..... fizeram' • pepfefeusson • 10/6/2024 • ",
"ja..... me..... fizeram • ciroel • 10/6/2024 • ",
"para, eu To proibido de realizar sucção • ciroel • 10/6/2024 • ",
"eu gosTo de comer o esTrelinha games enquanTo eu vejo • pepfefeusson • 10/6/2024 • ",
"a cara do bonnie ali na esquerda fazendo um 'UAU, isso nao é uma xoxota, é uma showxota, vc ta de parabéns' • pepfefeusson • 10/5/2024 • ",
"como eu queria estar, peituda e morta • ciroel • 10/1/2024 • ",
"comer lentilha e cu • pepfefeusson • 10/1/2024 • ",
"Como poe camisinha • ciroel • 9/27/2024 • ",
"@• pepfefeusson mas eu sou o viado games • pepfefeusson • 9/26/2024 • ",
"'Evan' is the ideal gender neutral name. Because it could be short for 'Evangelion' (boy name), or it could be short for 'Evanescence' (girl name) • pepfefeusson • 9/25/2024 • ",
"Fui chamado de coringa pelo rapper do trem, melhor que a última vez que ele me chamou de cabeça de alface • pepfefeusson • 9/20/2024 • ",
"fazendo arquiteturashaming • pepfefeusson • 9/4/2024 • ",
"infelizmente vai se aposentar a professora do meu departamento que em determinada aula de geotecnologia fazia doxxing de todos na sala numa atividade • pepfefeusson • 9/4/2024 • ",
"ia o bolsonaro na casa do N dar aula de educação fisica pra ele • pepfefeusson • 9/4/2024 • ",
"#paipresente • pepfefeusson • 8/16/2024 • ",
"tua casa tetm mosquitto? • pepfefeusson • 8/16/2024 • ",
"eu iniciei um curso de espanhol da faculdade e eu fiquei com vergonha de dizer q minha experiencia em espanhol era flertar com mexicano • pepfefeusson • 8/12/2024 • ",
"meu povo o cuscuz ta OOOAAAHN • pepfefeusson • 8/12/2024 • ",
"eu acho que ttu ta sendo mt transfóbico • ciroel • 8/7/2024 • ",
"OFICINA DE BOQUETE PARAFUSO CLICA AQUI apoia.se/stel • pepfefeusson • 8/6/2024 • ",
"metade disso nem é cidade, é distúrbio mental • ciroel • 8/5/2024 • ",
" ky de menta • ciroel • 8/5/2024 • ",
"SHIBARI, BDSM, ARTE, PUNK, SONIC, RPG, ARTPOP, CAOS, NEON, WALUIGI, QUEER, AGÊNERO, TF2, SODOMIA, SATÃ, VÍRUS, MACHINARIUM, COURO, XXX, LUA, PLUTÃO, LSD, UGLY SEASON, DOOM, SEGA, PQP! • ciroel • 7/25/2024 • ",
"toadofsky do caralho • ciroel • 7/17/2024 • ",
"oi gente • pepfefeusson • 7/16/2024 • ",
"próximo que comentar é viado • pepfefeusson • 7/16/2024 • ",
"abre na camera maior pra gentte ouvir melhor • ciroel • 7/3/2024 • ",
"'smt' 'eu ja vi a speedrun' • pepfefeusson • 7/2/2024 • ",
"cu de idosa memes • pepfefeusson • 6/18/2024 • ",
"@pepfefeusson @pepfefeusson @pepfefeusson tu tem um ódio tão genuíno por mim • pepfefeusson • 6/17/2024 • ",
"@ciroel celeste ou agencia banrisul • pepfefeusson • 6/13/2024 • ",
"AI É NIVER DA minha amiga, esqueci • pepfefeusson • 6/12/2024 • ",
"eu fazendo batalha de rap cmg no espelho [nota do editor: o stel começou cantar musica do capital inicial] • ciroel • 6/11/2024 • ",
"manda pro roberto 'e o cuzinho, ja deu hj?' • pepfefeusson • 6/5/2024 • ",
"escola sem partido • ciroel • 5/31/2024 • ",
"imagina perder o pé dentro do cu de alguém • pepfefeusson • 5/29/2024 • ",
"ce sabia que cárcere de ave é proibido? libera a piriquita ai • pepfefeusson • 5/28/2024 • ",
"[NORMAL] Jerk Off pp 10/10 • pepfefeusson • 5/24/2024 • ",
"AEOOOO desenhei uma mão e se parece com uma mão • pepfefeusson • 5/23/2024 • ",
"eu quelo comer metagranitos • pepfefeusson • 5/21/2024 • ",
"'ain, chupar água da calcinha no varal é coisa de gente feia' eu sendo horrorosa: • pepfefeusson • 5/20/2024 • ",
"'Veni Vidi Vixi' - Júlio César • pepfefeusson • 5/20/2024 • ",
"a gente ttem que se matar • pepfefeusson • 5/14/2024 • ",
"biri bibiri, biri bibaro, transformo vc num largo • pepfefeusson • 5/13/2024 • ",
"-Freud • ciroel • 5/12/2024 • ",
"'mete marcha, mete a pica, mete a lingua no meu cu, me pega pelos cabelos, depois chupa meu piru' • ciroel • 5/12/2024 • ",
"sim amigo, sou programador, me especializo nas linguagens PEITON, XANASCRIPT e PL/SQL (PERERECAS LARGAS, SÓ QUERO LAMBER)  O_o  • ciroel • 5/12/2024 • ",
"ou essa versão da história • ciroel • 5/12/2024 • ",
"QUANDO ESTÁS NA XAROCA E À PIÇA SALTA FORA E BATE VIOLENTAMENTE CONTRA A NALGA = parnasianismo dos memes • pepfefeusson • 5/9/2024 • ",
"Depende do signo do bb • ciroel • 5/7/2024 • ",
"sometimes batata palha com ketchup is janta • pepfefeusson • 4/26/2024 • ",
"BLJ na costela do viado • pepfefeusson • 4/25/2024 • ",
"Stelytle -> Santo Elytle • pepfefeusson • 4/24/2024 • ",
"Interjeição é o reino protista das classes gramaticais. • pepfefeusson • 4/24/2024 • ",
"VC PREFERIRIA: Um filho gay vs Sopinha de tomate hummmnn • pepfefeusson • 4/24/2024 • ",
"curirica é o BLJ do sexo • pepfefeusson • 4/24/2024 • ",
"Perna de perereca, cabeça de pirulito, faz com que essa novinha me dê o priquito • pepfefeusson • 4/23/2024 • ",
"Toda vez eu vou escrever @pep e sai @pqp • pepfefeusson • 4/23/2024 • ",
"OS BEATLES, Jingo, Ringo, Pingo e Gingo • pepfefeusson • 4/22/2024 • ",
"EU E MEU PARÇA NOS Escondendo no brinquedo da Anitta • pepfefeusson • 4/22/2024 • ",
"disse a fundação • ciroel • 4/12/2024 • ",
"AYOOOO #Mijo • ciroel • 4/12/2024 • ",
"Boca de piscininha • ciroel • 4/12/2024 • ",
"sugestão de alongamento = abrir os glúteos com as palmas das mãos bem esticado • ciroel • 4/12/2024 • ",
"sdds da época dos funks de adverbio de modo • pepfefeusson • 4/12/2024 • ",
"Patrick got the bong de caveira • pepfefeusson • 4/10/2024 • ",
"bigodão de varrer xereca • pepfefeusson • 4/10/2024 • ",
"tinha sturdy • ciroel • 4/9/2024 • ",
"#PARTIU #LOLLAPAUZUDA2024 • pepfefeusson • 4/9/2024 • ",
"é oficial, abalou as placas cucetônicas • pepfefeusson • 4/8/2024 • ",
"@pepfefeusson eu encontro tua casa e deslizo uma palca de gelo de mijo por baixo da tua porta • pepfefeusson • 4/8/2024 • ",
" :( dano neutro  :)  dane • pepfefeusson • 4/5/2024 • ",
"OLA EU GOSTO DE SIRIRICA • pepfefeusson • 4/4/2024 • ",
"choveu = Claro sentando de joelhos com o cuzinho úmido n antena de internet • pepfefeusson • 4/4/2024 • ",
"tu habilidade bufa • ciroel • 3/25/2024 • ",
"voltei, fiz um bolo sem querer • ciroel • 3/25/2024 • ",
"eu nao █████ um swampert • ciroel • 3/25/2024 • ",
"eu acho que o adolescente medio é exposto a pornografias mais istantes hoje em dia • ciroel • 3/25/2024 • ",
"estágios do luto: negação: (tu gira.); raiva (GIRA!); barganha (tu gira?); depressão (girava...); aceitação (tu não gira) • ciroel • 3/22/2024 • ",
"tu tem um tato pra atrair sulista e viado no chat sensacional, streamer • pepfefeusson • 3/4/2024 • ",
"sera que consigo reembolso de gental jousting? • pepfefeusson • 3/4/2024 • ",
"Agora um mico: leão dourado • ciroel • 3/4/2024 • ",
"Agora um mico: leão dourado • pepfefeusson • 3/4/2024 • ",
"encontrando o ponto g do peido braçal • pepfefeusson • 3/4/2024 • ",
"depois de uma noite de ██████ e conversa com colegas da faculdade, eu anotei no google keep 'Henry Ford = Tom Nook', e eu NAO LEMBRO quala reflexão que eu tive pra 'fazer essa correlação' • pepfefeusson • 3/4/2024 • ",
"daí sla, o lula, o mandela, o tom nook e o long man • ciroel • 3/4/2024 • ",
"eu na moleira do nenê (faz crec) • pepfefeusson • 3/4/2024 • ",
"SEIOS • ciroel • 3/4/2024 • ",
 "Itaquaquecetuba - SP • ciroel • 3/1/2024 • ",
 "o after é onde? • ciroel • 3/1/2024 • ",
 "oi gente, boa noite R) parem de me xingar nos comentários que vcs não me conhecem ;P <3 , vcs nao sabem como eu sou, quem eu sou, vcs nem moram aonde eu moro vai se foder todo mundo :/ O_o :( :O , vai tomar no meio do cu caralho, XIU :| :| :| tou brava >( >( >( • pepfefeusson • 3/1/2024 • ",
"PUTA QUE PARIU reativei meu facebook, fudeu • pepfefeusson • 3/1/2024 • ",
"NU, instalou um punhetron3000 no pip boy • pepfefeusson • 2/27/2024 • ",
"xoxota.rar • pepfefeusson • 2/26/2024 • ",
"Assunto: lutar contra uma galinha toda vez que tiver que entrar num carro ou vencer no TCG pokémon contra o Nietzsche ? • pepfefeusson • 2/26/2024 • ",
"apaguei o vape na tua cabeça (quebr • ciroel • 2/23/2024 • ",
"é meu cu que te da tchau • ciroel • 2/23/2024 • ",
"TRES TETAS INDIVIDUAIS • ciroel • 2/23/2024 • ",
"que ódio, eu ja ouvi discografia de tipo, 7 delas ali • ciroel • 2/19/2024 • ",
"não é como se eu fosse professor de humanas • ciroel • 2/19/2024 • ",
"pensei que tava começando a tocar elis regina ... é sonic • ciroel • 2/19/2024 • ",
"pelado e de suspensório me sinto o chaves • ciroel • 2/12/2024 • ",
"A firmeza da minha sanidade - Foucault • ciroel • 2/12/2024 • ",
"09/02 tatuar un qrcode para pudim.com.br • ciroel • 2/12/2024 • ",
"08/02 Nóis Chupa Rabo • ciroel • 2/12/2024 • ",
"sujeitos a rola e ovo • ciroel • 2/3/2024 • ",
"nenhuma destes termos estão na bíblia • ciroel • 2/3/2024 • ",
"preciso de alguem rosa pra bater • ciroel • 2/3/2024 • ",
"tu sabe ta radical quando te pedem pra nao usar desodorante • ciroel • 2/3/2024 • ",
"ciro nao é personagem de touhou? a de gelo • ciroel • 2/2/2024 • ",
"placas bucetonicas aqui • ciroel • 2/2/2024 • ",
"PERA EU TENHO UMA IMAGEM PRA ISSO • ciroel • 2/2/2024 • ",
"musica peidosa • pepfefeusson • 1/26/2024 • ",
"ah meu, o gato do schwarzenegger • pepfefeusson • 1/26/2024 • ",
"A Travestis - Murro na Costela do Viado • pepfefeusson • 1/25/2024 • ",
"AYOOO @Estileto abre duas instancias do emulador, joga ambas, mas diz que uma é o raul • pepfefeusson • 1/24/2024 • ",
"!apoia e !atrapalha • pepfefeusson • 1/23/2024 • ",
"HMMMMmm batata da perna *mastiga milimetricamente\ • pepfefeusson • 1/23/2024 • ",
"onde o sanduiche de buceta entre no alinhamento moral? • pepfefeusson • 1/22/2024 • ",
"eu vou dar meu cuuuu,e o meu chimarrããaao • pepfefeusson • 1/22/2024 • ",
"pisque o cu rapidamente 120bpm • pepfefeusson • 1/22/2024 • ",
"Vidrinho Summon Spell necronominom pesquisar • pepfefeusson • 1/22/2024 • ",
"musica de roubar o bolo da vizinha que ta comicamente esfriando na janela • pepfefeusson • 1/22/2024 • ",
"vou te pagar uma pizza pra tu me liberar um excel disso quando chegar em 100 • pepfefeusson • 1/22/2024 • ",
"NFT = Nóis Fuma Tora • pepfefeusson • 1/19/2024 • ",
"o Tabuu ouvindo Tom Jobin antes dos eventos de Smash Brawl • pepfefeusson • 1/19/2024 • ",
"[Emoji de pato] <-- TADINHO • pepfefeusson • 1/18/2024 • ",
"vai começar a lactação • pepfefeusson • 1/17/2024 • ",
"anal giratório no skate • pepfefeusson • 1/16/2024 • ",
"fallout nv unlock mamar o cesar dialogo choice pesquisar • pepfefeusson • 1/16/2024 • ",
"SUGADELA TUPI GUARANÍTICA • pepfefeusson • 1/15/2024 • ",
"URGENTE [alerta][alerta][alerta] FOI ENCONTRADO O PRIMEIRO CASO DE EBOLA EM SÃO PAULO  :O  :O  :O  :O  :O  :O  :O  :O  :O  :O  :O  :O  :O  :O  EBOLA NA REDE DO SÃO PAULO KKKKKKKKKKKKKKKKKK • pepfefeusson • 1/15/2024 • ",
"um cunete crash bandicoot? • pepfefeusson • 1/15/2024 • ",
"sucatta = boquete em italiano • pepfefeusson • 1/12/2024 • ",
"Louro josé morreu em 2020, mr house nasceu em 2020, bem vindo de volta louro jose • pepfefeusson • 1/12/2024 • ",
"Lula, por favor, libere o webnamoro • pepfefeusson • 1/12/2024 • ",
"Raul é mto sub mds • pepfefeusson • 1/12/2024 • ",
"usa o raul igual knuckles chaotix • pepfefeusson • 1/12/2024 • ",
"D-I-V-I-R-T-A-S-E [menina]Pai to indo na festa. [homem]Cê vai beber? [menina]Não. [homem]Vai fumar? [menina]Não. [homem]Vai usar droga? [menina]Não. [homem]Vai transar? [menina]Não. [homem]Então fica em casa, Caraii...  :D  :D  :D  :D  :D  • pepfefeusson • 1/5/2024 • ",
"vo comer brita • pepfefeusson • 1/5/2024 • ",
"baly é mijo o hulk = pepsi é adoçada com feto • pepfefeusson • 1/4/2024 • ",
"Deus da Bíblia™ ©Marvel • pepfefeusson • 1/4/2024 • ",
"a mente neurodivergente funciona em modos • pepfefeusson • 1/2/2024 • ",
"todo mundo tem pereba, só o austronauta que nao tem • pepfefeusson • 1/2/2024 • ",
"CAUTION risk of gabiru attack • pepfefeusson • 1/2/2024 • ",
"tu MIL POR CENTO vai mandar uns cueca cuela quando for pra italia • pepfefeusson • 1/2/2024 • ",
"tirou minha kalsinha e meteu o GAMEPLAY DE DUOLINGO • pepfefeusson • 1/2/2024 • ",
"batom de bigode = oral em cola branca • pepfefeusson • 1/1/2024 • ",
"essa vai pra video cassetadas • pepfefeusson • 12/29/2023 • ",
"remix do murro na costela do viado • pepfefeusson • 12/29/2023 • ",
"eu amor meus amigors no conputador • pepfefeusson • 12/21/2023 • ",
"eu tirei uma nude tão bonita [+18][+18]100% mas não tenho pra quem mandar  :(  :(  :(  a nude  ;P ;P ;P uma foto do meu pauzão  um retrato do meu rabo  [pessego] [pessego] [pessego] num posso postar aqui né  :(  </3  a nude  R)  foto minha [o/] pelado [Grrr] será que alguém vai pedir pra ver? hmn hmn :) vou me oferecer aqui  ;P  • pepfefeusson • 12/14/2023 • ",
"deixa o Cucetinha PELADO AGR • pepfefeusson • 12/14/2023 • ",
"proximo fallout eles vao adicionar mulheres aí ta perdido • pepfefeusson • 12/12/2023 • ",
"cusex" "ele é liberal • pepfefeusson • 12/1/2023 • ",
"os peitinho amadeirados do Geno, O Boneco • pepfefeusson • 12/1/2023 • ",
"falando em eu, meu kbelo ta mto foda • pepfefeusson • 11/30/2023 • ",
"Josoaldo Jéssico. • pepfefeusson • 11/28/2023 • ",
"João, o Pede Picão :biting_lip: :biting_lip: :biting_lip: :biting_lip: • pepfefeusson • 11/24/2023 • ",
"JOÃO E O PÉ DE PICÃO • pepfefeusson • 11/24/2023 • ",
"bom diaaa sou novo grupo , vendo perfumes da Hinode e vende tênis Masculinos e feminino , se alguém tiver interesse chamar PV .... obrigado pela atenção se eu infligir alguma regra peço que os Adms me chamem antes de remover ... • pepfefeusson • 11/24/2023 • ",
"tom e jerry poderiam ter feito algo MUITO engraçado na tua escola • pepfefeusson • 11/24/2023 • ",
"tu nao é gay só pq nao chupa piroca pq meua migo • pepfefeusson • 11/24/2023 • "
    ]

    //mensagens.length
    var i = Math.floor(Math.random() * mensagens.length)
    return {
      statusCode: 200,
      body: mensagens[i],
    };
  };