BEGIN;
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Suco da bola de fogo esquerda do Charizard.', 'Uma bebida quente feita com uísque Fireball Cinnamon, grenadine, uísque escocês, Bacardi 151 e refrigerante de gengibre.', 'Fireball drink');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('A última Hyper Potion da celia.', 'Licor de fruta (vermelha, roxa ou transparente), Blue Curacao, Suco de fruta citrica.', 'China Blue Flex');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Uma taça tulipa de Ivysaurito.', '1 Rum, 1 Suco de limão, açucar, morangos, agua com gás, folhas de hortelã.', 'Mojito de morango.');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Água de Blastoise.', 'Vodka, Curaçao e Ginger Ale. Servido com dois canudos grandes.', 'Autoral Ciroel');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Um suculento Caldo de Cloyster.', 'Rum, açúcar, mirtilio (ou morangos), limão e hortelã, servido em copo roxo ou com gelo em formato de pérolas.', 'Amansa Sapatão');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Uma caneca de Gemadas dos irmões do Croc.', '1 gema, açúcar, leite quente, 2 Cachaça et canela em pó ', 'Gemada Quente com Cachaça');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Uma Batida de Tropius.', '2 bourbon Woodinville, 1 creme de coco, 1  creme de banana, 1/2 suco de limão,  hortelã', 'Miamian’s Julep');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Copada de Gobbo.', '50ml Baileys Irish Cream, 150 Café, chocolate granulado, leite.', 'Baileys Hot Irish Coffee');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Um Cosmopolitan Slowpoketail bem gelado.', '2 Vodka (ou citrus vodka), 1/2 tripple sec, 3/4 cranberry juice, suco de limão. ', 'Cosmopolitan cocktail.');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Sempre confiavel e clássico: Baly 4ever.', 'Whisky e Baly de qualquer sabor.', 'Autoria Ciroel e Cucetinha Arts');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Suco de Shuckle servido direto do casco.', 'Proscecco, Pure de pessego, suco de framboesa.', 'Bellini');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Água do Guaíba.', '2 partes de licor café pra 5 de vodka.', 'Black Russian');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Suor de Bowser fresco servido em um copo Collins.', '2 Back Rum, 3-5 Ginger Beer (ou Ale), 1/2 Suco de limão', 'Dark `n` Stormy');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Um copo de Seiva dos mamilos do Nuzleaf.', '1 1/2 Burbon ou Rye Whisky, 1 Campari, 1 Vinho bordo (ou 1/4 de porto), Hortelã. ', 'Boulevardier adaptado.');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Lagrimas de Croc servido em um vaso.', '2 Tequila, 1 1/2 Suco de laranja, 1 Suco de Toranja, 1 Suco de limão ou lima,  sal, Refrigerante de Toranja pra completar.', 'Cantaritos');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Uma taça de sereno de Butterfree.', '1 1/2 Vodka, 1 Curacao, 1 Grenadine, 1 Suco de limão, Sprite.', 'Purple Rain');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Um pouco de Mel de joelho de Beedrill.', '2 Gin, 1 Suco de limão siciliano, 1/2 Mel', 'Bee`s Knees Cocktail');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Un Ludicolo colocado y comprimido en una copa tulipán.', '1.5 Rum, 2 Leite de Coco, Suco de Abacaxi, 1/2 suco de limão.', 'Piña Colada.');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Uma taça de Boa Noite Jigglypuff.', '2 Vodka, 2 Yogurte de Morango, 2 Leite condençado, Morangos, ', 'Caipifruta de morango');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Um frescor de Gloom.', '3 Vinho Fortificado, 1 Crème de Cassis, Club Soda ou Agua com Gás, Folha de Hortelã', 'Vermouth Cassis');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Chá de Lama de Grimer servido em uma Tania Bulhões coleção Marquesa.', '1/2 Vodka, 1/2 Tequila, 1/2 Rum, 1/2 Gin, 1/2 Triple Sec, 1/2 Suco de limão de minas gerais, açucar, refrigerante de Cola.', 'Long Island Iced Tea');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Um copo americano de Raichu da Quebrada.', '2 Gin, 1 Vinho bordo (ou 1/4 de porto), 1 Suco de laranja, fatia de laranja. ', 'Bronx Cocktail');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Suco de pilha de Electrode.', '1 1/2 Campari, Açucar, Suco de Laranja', 'Garibaldi');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Uma xícara de Expresso Koffing. ', '1 1/2 Vodka, 1 Café expresso italiano gelado, 1 Creme de café (ou leite frio espumado + açucar mascavo).', 'Espresso Martini');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Chansey Club servida em uma caneca.', '2 Gin, 1/2 suco de limao, 1/2 Xarope de framboesa, 1 gema de ovo', 'Clover Club');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Gemidão de Starmie sevido no copo plastico.', '1/2 Sour Pussy Framboesa, 1/2 Blue Curaçao, Refrigerante de limao e suco de abacaxi ou oxicoco.', 'Pornstar');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Suquinho das asas de um Scyther esmagados', '12 folhas de manjericão, 2 Dry Gin, 1 Suco de limão siciliano, açucar', 'Gin Basil Smash');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Sorriso de Pikachu servido em um copo de requeijão.', '2 Tequila, Suco de laranja, Grenadine, Cereja Maraschino', 'Tequila Sunrise');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Um balde de Leite Cremoso de Tauros.', '1 1/2 Cachaça, 1 Suco de Abacaxi, Amareto, Licor de Amendoas, Açucar, Agua de coco com limão, Chantilly pra decorar. ', 'Coco Milky Way');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Um copo de Olhar de Julgamento de Lapras.', '1 1/2 Vodka, 1 Blue Curaçao, 1 Suco de limão, Sprite.', 'Blue Lagoon');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Um saqueria de Extratos Mil de Magikarp.', '2 saquê, açucar, morangos, suco de limão siciliano, meia fatia de laranja pra decorar', 'Saqueria de Morango');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Um copo de Pineco Sour', 'Licor de amarettto, suco de limão', 'Amaretto Sour');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Um susto de Taz`s Aviation', 'Gin, Licor de Maraschino, creme de violette, suco de limão siciliano. ', 'Aviation');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Tomando um Moscow Torchic direto de uma galocha.', '2 vodka (de preferencia de crambery), 4 Ginger Beer ou Ale, Suco de bergamota.', 'Moscow Mule de bergamota.');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Caneca de Caipiroska de Piplup.', '2 Vodka, 1 Blue Curaçao, Licor de Cassis, açucar mascavo', 'Caipiroska Azul adaptada.');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Xicara de metal de Petala Roselia.', '2 Cachaça, Açucar, Morango, Mirtilo, Suco de limão', 'Sunrise Azul com cachaça');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('Você bebe Gotta go fast! direto da boca do Sonic. ', 'Vodka, Blue Curacao, Baly tadala, Xarope de Mirtilo.', 'Autoral Ciroel');

INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('', '', 'Mexican Mule');
INSERT INTO tb_mini_bar(descricao, ingredientes, referencia) VALUES ('', '', '');


END;